atomic: Rename local __atomic_compare_exchange to avoid clash with builtins
Helps building with clang

Fixes

../db-5.3.28/src/dbinc/atomic.h:179:19: error: definition of builtin function '__atomic_compare_exchange'
static inline int __atomic_compare_exchange(

Upstream-Status: Pending

Signed-off-by: Khem Raj <raj.khem@gmail.com>

%% original patch: 0001-atomic-Rename-local-__atomic_compare_exchange-to-avo.patch